# the 0-th train script, for training with the original training set without val data.
ckpt_name="model0"
CUDA_VISIBLE_DEVICES=0,1,2,3,4 python -u train.py \
--learning_rate 0.000005 \
--batch_size 24 \
--ckpt_name ${ckpt_name}  \
--img_length_read 6 \
--data_dir_2d ./data/train_img \
--data_dir_2d_dev ./data/val_img \
--num_epochs 5 \
--train_filename_list ./data/train_total.csv \
>> logs/${ckpt_name}.log 

# the 1-th train script, for training with the original training set and val data with pseudo labels generated by the 0-th model.
ckpt_name="model1"
CUDA_VISIBLE_DEVICES=0,1,2,3,4 python -u train.py \
--learning_rate 0.000005 \
--batch_size 24 \
--ckpt_name ${ckpt_name}  \
--img_length_read 6 \
--data_dir_2d ./data/train_img \
--data_dir_2d_dev ./data/val_img \
--num_epochs 5 \
--train_filename_list ./data/train_gt_val_pseudo.csv \
>> logs/${ckpt_name}.log